watchers: []
watches:
  prompt-expert-test:
  - pattern: '*.md'
    agent: promptexpert
    args: security
    added_by: whichguy
    added_at: '2025-08-07T13:09:43.999683Z'
    pr: 18
  agentwatch-stateful-validation:
  - pattern: '*.md'
    agent: promptexpert
    args: security
    added_by: whichguy
    added_at: '2025-08-07T13:25:16.278381Z'
    pr: 19
excludes:
  agentwatch-stateful-validation: []
