watchers: []
watches:
  prompt-expert-test:
  - pattern: '*.md'
    agent: promptexpert
    args: security
    added_by: whichguy
    added_at: '2025-08-07T13:09:43.999683Z'
    pr: 18
  agentwatch-stateful-validation:
  - pattern: '*.css'
    agent: stylelint
    args: ''
    added_by: whichguy
    added_at: '2025-08-07T13:37:42.751367Z'
    pr: 19
    updated_by: whichguy
    updated_at: '2025-08-07T13:37:50.022928Z'
excludes:
  agentwatch-stateful-validation:
  - pattern: '*.js'
    agent: eslint
    excluded_by: whichguy
    excluded_at: '2025-08-07T13:34:53.825594Z'
    pr: 19
  - pattern: '*.py'
    agent: ruff
    excluded_by: whichguy
    excluded_at: '2025-08-07T13:35:39.031024Z'
    pr: 19
  - pattern: '*.test.js'
    agent: jest
    excluded_by: whichguy
    excluded_at: '2025-08-07T13:36:21.075683Z'
    pr: 19
  - pattern: node_modules/**
    agent: all
    excluded_by: whichguy
    excluded_at: '2025-08-07T13:38:05.253549Z'
    pr: 19
