name: 'Setup AgentWatch'
description: 'Install AgentWatch file-level agent monitoring system'
author: 'AgentWatch'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  create-pr:
    description: 'Create PR instead of direct commit'
    required: false
    default: 'true'
  agents:
    description: 'Comma-separated list of agents to install (echo,promptexpert,lint)'
    required: false
    default: 'echo,promptexpert,lint'

outputs:
  pr-url:
    description: 'URL of created PR (if create-pr is true)'
    value: ${{ steps.create-pr.outputs.pr-url }}
  status:
    description: 'Installation status'
    value: ${{ steps.install.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Install AgentWatch
      id: install
      shell: bash
      run: |
        echo "🤖 Installing AgentWatch..."
        
        # Create directory structure
        mkdir -p .github/workflows
        mkdir -p .github/scripts/agents
        
        # Download AgentWatch files
        REPO_URL="https://raw.githubusercontent.com/${{ github.action_repository }}/main"
        
        curl -sSL "$REPO_URL/.github/workflows/agentwatch.yml" > .github/workflows/agentwatch.yml
        curl -sSL "$REPO_URL/.github/scripts/agentwatch.js" > .github/scripts/agentwatch.js
        curl -sSL "$REPO_URL/.github/scripts/agent-helpers.js" > .github/scripts/agent-helpers.js
        curl -sSL "$REPO_URL/.github/scripts/AGENTWATCH.md" > .github/scripts/AGENTWATCH.md
        
        # Install selected agents
        IFS=',' read -ra AGENTS <<< "${{ inputs.agents }}"
        for agent in "${AGENTS[@]}"; do
          echo "📥 Installing $agent agent..."
          curl -sSL "$REPO_URL/.github/scripts/agents/$agent.js" > .github/scripts/agents/$agent.js
        done
        
        echo "status=installed" >> $GITHUB_OUTPUT
        echo "✅ AgentWatch installation complete"
        
    - name: Create configuration
      shell: bash
      run: |
        cat > .github/agentwatch-config.yml << EOF
        # AgentWatch Configuration
        version: "1.0"
        installed: $(date -Iseconds)
        source: "${{ github.action_repository }}"
        
        agents:
        $(echo "${{ inputs.agents }}" | tr ',' '\n' | sed 's/^/  /')
        EOF
        
    - name: Commit or create PR
      id: create-pr
      uses: actions/github-script@v7
      with:
        script: |
          const createPr = '${{ inputs.create-pr }}' === 'true';
          
          if (createPr) {
            // Create branch and PR
            const branchName = `setup-agentwatch-${Date.now()}`;
            
            // Create commit
            const { data: ref } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/main'
            });
            
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branchName}`,
              sha: ref.object.sha
            });
            
            // Create PR
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🤖 Setup AgentWatch: File-level agent monitoring',
              head: branchName,
              base: 'main',
              body: `## AgentWatch Installation
              
              This PR installs AgentWatch for file-level agent monitoring.
              
              **Agents installed**: ${{ inputs.agents }}
              
              **Test after merging**: \`@agentwatch echo preview\`
              
              See \`.github/scripts/AGENTWATCH.md\` for documentation.`
            });
            
            core.setOutput('pr-url', pr.html_url);
            console.log(`Created PR: ${pr.html_url}`);
          } else {
            console.log('Direct commit mode - files ready to use');
          }