name: AgentWatch PR Trigger
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-watchers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check and Run
        uses: actions/github-script@v7
        with:
          script: |
            console.log('AgentWatch PR Trigger started');
            console.log('Event:', context.eventName);
            console.log('PR:', context.payload.pull_request?.number);
            
            // Quick test - just add a label to show it's working
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['agentwatch:checking']
              });
              console.log('Label added successfully');
            } catch (e) {
              console.log('Error adding label:', e.message);
            }