name: AgentWatch Stateful
# Maintains watch patterns in .github/agentwatch.yml

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write      # Required to update .github/agentwatch.yml
  pull-requests: write # Required to comment on PRs
  issues: write        # Required for issue comments

jobs:
  process-command:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '@agent-')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr
        run: |
          PR_DATA=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          echo "head_ref=$(echo "$PR_DATA" | jq -r .head.ref)" >> $GITHUB_OUTPUT
          echo "base_ref=$(echo "$PR_DATA" | jq -r .base.ref)" >> $GITHUB_OUTPUT
          echo "head_sha=$(echo "$PR_DATA" | jq -r .head.sha)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python for YAML handling
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install PyYAML
        run: pip install pyyaml
          
      - name: Process AgentWatch command
        id: process
        run: |
          cat > process_command.py << 'EOF'
          import yaml
          import json
          import sys
          import re
          import os
          from datetime import datetime
          
          comment = """${{ github.event.comment.body }}"""
          user = "${{ github.event.comment.user.login }}"
          pr_number = ${{ github.event.issue.number }}
          
          config_file = ".github/agentwatch.yml"
          
          # Ensure .github directory exists
          os.makedirs(".github", exist_ok=True)
          
          # Load existing config or create new
          if os.path.exists(config_file):
              with open(config_file, 'r') as f:
                  config = yaml.safe_load(f) or {"version": 1, "watches": []}
          else:
              config = {"version": 1, "watches": []}
          
          # Parse command
          output = {"command": "unknown", "message": ""}
          
          # @agent-watch pattern agent @ args
          watch_match = re.search(r'@agent-watch\s+([^\s]+)\s+([^\s]+)(?:\s+@\s+(.+))?', comment)
          if watch_match:
              pattern = watch_match.group(1)
              agent = watch_match.group(2)
              args = watch_match.group(3) or ""
              
              # Check if this watch already exists
              existing = None
              for watch in config["watches"]:
                  if watch["pattern"] == pattern and watch["agent"] == agent:
                      existing = watch
                      break
              
              if existing:
                  # Update existing watch
                  existing["args"] = args
                  existing["updated_by"] = user
                  existing["updated_at"] = datetime.utcnow().isoformat() + "Z"
                  output["message"] = f"Updated existing watch: {pattern} -> {agent}"
              else:
                  # Add new watch
                  config["watches"].append({
                      "pattern": pattern,
                      "agent": agent,
                      "args": args,
                      "added_by": user,
                      "added_at": datetime.utcnow().isoformat() + "Z",
                      "pr": pr_number
                  })
                  output["message"] = f"Added new watch: {pattern} -> {agent}"
              
              output["command"] = "watch"
              output["pattern"] = pattern
              output["agent"] = agent
              output["args"] = args
              
              # Save config
              with open(config_file, 'w') as f:
                  yaml.dump(config, f, default_flow_style=False, sort_keys=False)
          
          # @agent-unwatch agent pattern
          unwatch_match = re.search(r'@agent-unwatch\s+([^\s]+)\s+([^\s]+)', comment)
          if unwatch_match:
              agent = unwatch_match.group(1)
              pattern = unwatch_match.group(2)
              
              # Remove matching watch
              original_count = len(config["watches"])
              config["watches"] = [w for w in config["watches"] 
                                  if not (w["pattern"] == pattern and w["agent"] == agent)]
              
              if len(config["watches"]) < original_count:
                  output["message"] = f"Removed watch: {pattern} -> {agent}"
                  # Save config
                  with open(config_file, 'w') as f:
                      yaml.dump(config, f, default_flow_style=False, sort_keys=False)
              else:
                  output["message"] = f"No matching watch found: {pattern} -> {agent}"
              
              output["command"] = "unwatch"
              output["pattern"] = pattern
              output["agent"] = agent
          
          # @agent-list
          if "@agent-list" in comment:
              output["command"] = "list"
              output["watches"] = config["watches"]
              output["message"] = f"Found {len(config['watches'])} active watches"
          
          # Output for GitHub Actions
          print(f"::set-output name=command::{output['command']}")
          print(f"::set-output name=message::{output['message']}")
          if "pattern" in output:
              print(f"::set-output name=pattern::{output['pattern']}")
          if "agent" in output:
              print(f"::set-output name=agent::{output['agent']}")
          if "args" in output:
              print(f"::set-output name=args::{output['args']}")
          if "watches" in output:
              print(f"::set-output name=watches::{json.dumps(output['watches'])}")
          EOF
          
          python process_command.py
          
      - name: Commit configuration changes
        if: steps.process.outputs.command == 'watch' || steps.process.outputs.command == 'unwatch'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .github/agentwatch.yml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update AgentWatch configuration
            
            Command: @agent-${{ steps.process.outputs.command }}
            Pattern: ${{ steps.process.outputs.pattern }}
            Agent: ${{ steps.process.outputs.agent }}
            Triggered by: @${{ github.event.comment.user.login }}"
            
            git push origin ${{ steps.pr.outputs.head_ref }}
          fi
          
      - name: Trigger agent workflow
        if: steps.process.outputs.command == 'watch'
        run: |
          echo "Would trigger ${{ steps.process.outputs.agent }} for pattern ${{ steps.process.outputs.pattern }}"
          
          # Trigger the specific agent workflow if it exists
          AGENT="${{ steps.process.outputs.agent }}"
          PATTERN="${{ steps.process.outputs.pattern }}"
          ARGS="${{ steps.process.outputs.args }}"
          
          # For prompt-expert, post the command
          if [ "$AGENT" = "promptexpert" ]; then
            gh pr comment ${{ github.event.issue.number }} \
              --body "@promptexpert $ARGS analyze files matching $PATTERN"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Post status comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const command = '${{ steps.process.outputs.command }}';
            const message = '${{ steps.process.outputs.message }}';
            const pattern = '${{ steps.process.outputs.pattern }}';
            const agent = '${{ steps.process.outputs.agent }}';
            const args = '${{ steps.process.outputs.args }}';
            
            let body = '';
            
            if (command === 'watch') {
              body = `✅ **AgentWatch Pattern Saved**
              
              📁 **Pattern**: \`${pattern}\`
              🤖 **Agent**: ${agent}
              ⚙️ **Args**: ${args || 'none'}
              📝 **Config**: Updated \`.github/agentwatch.yml\` on branch \`${{ steps.pr.outputs.head_ref }}\`
              
              ${message}
              
              This pattern is now being monitored. Use \`@agent-unwatch ${agent} ${pattern}\` to remove.`;
              
            } else if (command === 'unwatch') {
              body = `✅ **AgentWatch Pattern Removed**
              
              ${message}
              
              📝 **Config**: Updated \`.github/agentwatch.yml\``;
              
            } else if (command === 'list') {
              const watches = ${{ steps.process.outputs.watches || '[]' }};
              
              if (watches.length === 0) {
                body = `📋 **No Active AgentWatch Patterns**
                
                Use \`@agent-watch <pattern> <agent> @ <args>\` to add patterns.`;
              } else {
                body = `📋 **Active AgentWatch Patterns**\n\n`;
                watches.forEach((w, i) => {
                  body += `${i + 1}. **Pattern**: \`${w.pattern}\`\n`;
                  body += `   **Agent**: ${w.agent}`;
                  if (w.args) body += ` | **Args**: ${w.args}`;
                  body += `\n   **Added by**: @${w.added_by} on ${new Date(w.added_at).toLocaleDateString()}\n\n`;
                });
              }
            } else {
              body = `❌ **Unknown AgentWatch Command**
              
              Available commands:
              - \`@agent-watch <pattern> <agent> @ <args>\` - Add pattern
              - \`@agent-unwatch <agent> <pattern>\` - Remove pattern
              - \`@agent-list\` - List all patterns`;
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
            
  # Process file changes when PR is updated
  check-patterns:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        
      - name: Check for watch patterns
        run: |
          if [ -f ".github/agentwatch.yml" ]; then
            echo "AgentWatch configuration found"
            cat .github/agentwatch.yml
            
            # Here we would check changed files against patterns
            # and trigger appropriate agents
          else
            echo "No AgentWatch configuration in this PR"
          fi